### ISSUE TITLE
Make blog preview "Read more" link more prominent

### ISSUE THREAD

**Issue by kevinwang** [Team694/team694.github.io#88]
The "Read more" link is not as visible as I would have hoped. I didn't realize at all that there was more to this article until after I clicked on the title.

![](http://f.kev.wang/i/HZKkqx.png)

Here's a rough draft of a potential improvement:

![](http://f.kev.wang/i/6YauHV.png)

![](http://f.kev.wang/i/fRQdkj.png)

I added this styling to the `p` element containing the "Read more" link:

```css
element.style {
    padding-left: 20px;
    background-color: #eee;
    line-height: 2.5em;
    border-radius: 5px;
}
```

You would probably want to use the same shade of gray as the navbar, but I'm too lazy to update the screenshots...
